# ─────────────────────────────────────────────
#  byteGirl — Documentation
# ─────────────────────────────────────────────

[project]
logo = "images/logo.png"
site_name = "byteDocs"
site_description = "Security notes, homelab setup & methodology"
site_author = "byteGirl"
copyright = "&copy; 2026 byteDoc"
site_url = "https://docu.bytegirl.be"
extra_css = ["stylesheets/extra.css"]

# Enables icons + emojis (required for the `icon:` frontmatter)
[project.markdown_extensions.attr_list]
[project.markdown_extensions.pymdownx.emoji]
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]

[project.theme]
favicon = "img/favicon.png"
features = [
    "navigation.footer",
    "search.highlight",
    "content.code.copy",      # copy button 
    "content.code.select",    # lets me select/link line ranges
    "navigation.top",         # back-to-top button
    "navigation.instant",     # SPA-style instant page loads
  ]
palette.scheme = "slate"
palette.primary = "custom"
palette.accent = "custom"
font.text = "JetBrains Mono"
font.code = "JetBrains Mono"

[project.theme.icon]
logo = "lucide/terminal"

